name: Build and Publish Single File Package

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
      pull-requests: write
      issues: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      continue-on-error: true
      
    - name: Build single file package
      run: npm run build:single
      
    - name: Verify build output
      run: |
        echo "Build completed successfully!"
        ls -la dist/
        echo "Single file build size:"
        du -h dist/index.html
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: single-file-build
        path: dist/index.html
        retention-days: 30
        
    - name: Setup Pages (on main branch only)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/configure-pages@v4
      
    - name: Upload to GitHub Pages (on main branch only)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
        
    - name: Deploy to GitHub Pages (on main branch only)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: Comment on PR with build info (on PR only)
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = './dist/index.html';
          const stats = fs.statSync(path);
          const fileSizeInKB = Math.round(stats.size / 1024);
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🎉 **Build Successful!**
            
            ✅ Single file package built successfully
            📦 File size: ${fileSizeInKB} KB
            📁 Artifact: \`single-file-build\`
            
            The built package is available as a downloadable artifact in this workflow run.`
          });

  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Run tests
      run: npm test:jcc2
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30